# Generated by Django 4.2.5 on 2023-11-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_img', models.ImageField(blank=True, upload_to='store_images/')),
                ('about', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
