# Generated by Django 4.2.5 on 2023-11-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_item_alter_store_store_img_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
