# Generated by Django 4.2.5 on 2023-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_sheet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='items',
            field=models.ManyToManyField(related_name='sheets', to='project_app.item'),
        ),
    ]
