name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          

      - name: Run Model Unit Tests
        run: |
          python manage.py test project_app.tests.ModelsTest
      
      - name: Run Forms Unit Tests
        run: |
          python manage.py test project_app.tests.FormsTest

      - name: Run Selenium Tests
        run: |
          python manage.py runserver
          background: true
          sleep 5
          python manage.py test project_app.tests.HostTest
          python manage.py test project_app.tests.LoginFormTest
          python manage.py test project_app.tests.AddItemToSheetTest

